---
title: "Extract numbers/stats for supplemental information section"
output: html_notebook
---

```{r setup, include=FALSE, results='hide'}
knitr::opts_chunk$set(echo = TRUE)
options(warn = -1)
root <- rprojroot::find_root(".git/index"); 
source(file.path(root, "src", "grace", "init.R"))
```

Now load the data for the macrophage images.

```{r}
val <- read_csv(file=file.path(CANDESCENCE, "performance/grace_macro", "all_events_results_biglittlelittle_type_val_thresh_0.2.csv"))
train <-  read_csv(file=file.path(CANDESCENCE, "performance/grace_macro", "all_events_results_biglittlelittle_type_train_thresh_0.2.csv"))
test <-  read_csv(file=file.path(CANDESCENCE, "performance/grace_macro", "complete_test_events_biglittlelittle_thresh_0.2.csv"))

```
```{r}
counts_train <- train %>% group_by(gt_class) %>% summarise(n=n()) %>% print

```


```{r}
counts_val <- val %>% group_by(gt_class) %>% summarise(n=n()) %>% print

```

```{r}
test_val <- test %>% group_by(dt_class) %>% summarise(n=n()) %>% print

```

Now load the TC images
```{r}
val <- read_csv(file=file.path(CANDESCENCE, "performance/grace_tc", "all_events_results_chosenone_type_val_thresh_0.3.csv"))
train <-  read_csv(file=file.path(CANDESCENCE, "performance/grace_tc", "all_events_results_chosenone_type_train_thresh_0.3.csv"))
test <-  read_csv(file=file.path(CANDESCENCE, "performance/grace_tc", "complete_test_events_chosenone_thresh_0.3.csv"))
```

```{r}
counts_train <- train %>% group_by(gt_class) %>% summarise(n=n()) %>% print

```



```{r}
counts_val <- val %>% group_by(gt_class) %>% summarise(n=n()) %>% print

```

```{r}
test_val <- test %>% group_by(dt_class) %>% summarise(n=n()) %>% print

```

